/*****************************************************/
/*                                                   */
/*             Generated by OSD Designer             */
/*                  Made by Hidegon                  */
/*  OSD Designer: https://HidegonSan.github.io/OSD/  */
/*                                                   */
/*****************************************************/

#include <CTRPluginFramework.hpp>
#include <cmath>

namespace CTRPluginFramework {
void DrawLine(const Screen &scr, int srcX, int srcY, int dstX, int dstY, const Color &color);
void DrawRectPlus(const Screen &scr, u32 posX, u32 posY, u32 width, u32 height, const Color &color, bool filled, int origin);
void DrawPlus(const Screen &scr, const std::string &str, u32 posX, u32 posY, u32 borderWidth, u32 padding, const Color &foreground, const Color &background, const Color &border, int fontAlign, int origin);
void DrawSysfontPlus(const Screen &scr, const std::string &str, u32 posX, u32 posY, u32 borderWidth, u32 padding, const Color &foreground, const Color &background, const Color &border, bool fillBackground, int fontAlign, int origin);
float DegreeToRadian(float degree);
void DrawCircle(const Screen &scr, u32 x, u32 y, u32 radiusStart, u32 radiusEnd, int start, int end, const Color &color, int origin);

void DrawDiamond(const Screen &scr, u16 leftX, u16 leftY, u16 rightX, u16 rightY, const Color &color, bool filled);
}  // namespace CTRPluginFramework